# Generated by Django 5.2.7 on 2025-10-23 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title_template', models.CharField(help_text='Template for title with {variables}', max_length=200)),
                ('message_template', models.TextField(help_text='Template for message with {variables}')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('training', 'Model Training'), ('prediction', 'Prediction'), ('system', 'System')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('training', 'Model Training'), ('prediction', 'Prediction'), ('system', 'System')], default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_global', models.BooleanField(default=False, help_text='Show to all users')),
                ('is_read', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether notification is still active')),
                ('auto_expire', models.BooleanField(default=True, help_text='Auto-expire after expiry_date')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='When notification expires', null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate to when clicked')),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, help_text='ML model name if applicable', max_length=100)),
                ('operation_id', models.CharField(blank=True, help_text='Operation ID for tracking', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('user', models.ForeignKey(blank=True, help_text='Target user (null for all users)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='machine_lea_user_id_bfb584_idx'), models.Index(fields=['notification_type'], name='machine_lea_notific_a89160_idx'), models.Index(fields=['is_active', 'created_at'], name='machine_lea_is_acti_c05cde_idx')],
            },
        ),
    ]
