# Generated by Django 5.2.7 on 2025-10-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_key', models.SlugField(unique=True)),
                ('icon', models.CharField(max_length=10)),
                ('icon_color', models.CharField(default='#fff', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('metric_value', models.CharField(blank=True, max_length=50, null=True)),
                ('metric_label', models.CharField(blank=True, max_length=50, null=True)),
                ('metric_color', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_html', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
